CREATE TABLE ras_outcome_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    situation_id    VARCHAR(255) NOT NULL,
    correlation_key VARCHAR(255) NOT NULL,
    tenancy_id      VARCHAR(255) NOT NULL,
    outcome_label   VARCHAR(255) NOT NULL,
    classification  VARCHAR(20)  NOT NULL,
    closed_at       TIMESTAMP    NOT NULL,
    case_id         UUID         NOT NULL,
    CONSTRAINT uq_outcome_case_id UNIQUE (case_id)
);

CREATE INDEX idx_outcome_situation_tenant
    ON ras_outcome_record (situation_id, tenancy_id, closed_at);

CREATE INDEX idx_outcome_suppression
    ON ras_outcome_record (situation_id, correlation_key, tenancy_id,
                           classification, closed_at DESC);
